/**
 * Secret Detection Rule Definitions
 * Each rule defines an exact signature pattern, provider metadata, and severity.
 */

export const SEVERITY = {
  CRITICAL: 'critical',
  HIGH: 'high',
  MEDIUM: 'medium',
  LOW: 'low',
};

export const RULES = [
  {
    id: 'aws-access-key-id',
    name: 'AWS Access Key ID',
    provider: 'Amazon Web Services',
    severity: SEVERITY.CRITICAL,
    pattern: /\b((?:AKIA|ABIA|ACCA|ASIA)[0-9A-Z]{16})\b/g,
    description: 'Permanent or session credentials for AWS API authentication.',
  },
  {
    id: 'aws-secret-access-key',
    name: 'AWS Secret Access Key',
    provider: 'Amazon Web Services',
    severity: SEVERITY.CRITICAL,
    pattern: /(?:aws_secret_access_key|aws_secret_key|secret_access_key)\s*[:=]\s*["']?([A-Za-z0-9/+=]{40})["']?/gi,
    matchGroup: 1,
    description: 'Secret component of AWS IAM authentication credentials.',
  },
  {
    id: 'github-pat-classic',
    name: 'GitHub Personal Access Token (Classic)',
    provider: 'GitHub',
    severity: SEVERITY.CRITICAL,
    pattern: /\b(gh[pousr]_[A-Za-z0-9_]{36,255})\b/g,
    description: 'Personal access token granting repository/account access.',
  },
  {
    id: 'github-pat-fine-grained',
    name: 'GitHub Fine-Grained Personal Access Token',
    provider: 'GitHub',
    severity: SEVERITY.CRITICAL,
    pattern: /\b(github_pat_[A-Za-z0-9_]{30,120})\b/g,
    description: 'Resource-scoped fine-grained GitHub access token.',
  },
  {
    id: 'openai-api-key',
    name: 'OpenAI API Key',
    provider: 'OpenAI',
    severity: SEVERITY.CRITICAL,
    pattern: /\b(sk-(?:proj-)?[A-Za-z0-9_\-]{32,128})\b/g,
    description: 'Secret API key for OpenAI GPT and embedding endpoints.',
  },
  {
    id: 'anthropic-api-key',
    name: 'Anthropic API Key',
    provider: 'Anthropic',
    severity: SEVERITY.CRITICAL,
    pattern: /\b(sk-ant-[a-zA-Z0-9_\-]{40,128})\b/g,
    description: 'Secret key for Anthropic Claude model invocations.',
  },
  {
    id: 'stripe-secret-key',
    name: 'Stripe Secret Key',
    provider: 'Stripe',
    severity: SEVERITY.CRITICAL,
    pattern: /\b([rs]k_live_[0-9a-zA-Z]{24,99})\b/g,
    description: 'Live Stripe API secret key capable of financial charges.',
  },
  {
    id: 'stripe-publishable-key',
    name: 'Stripe Publishable Key',
    provider: 'Stripe',
    severity: SEVERITY.LOW,
    pattern: /\b(pk_live_[0-9a-zA-Z]{24,99})\b/g,
    description: 'Live publishable key for client-side Stripe integrations.',
  },
  {
    id: 'google-api-key',
    name: 'Google Cloud / Maps API Key',
    provider: 'Google',
    severity: SEVERITY.HIGH,
    pattern: /\b(AIza[0-9A-Za-z\-_]{35})\b/g,
    description: 'Universal Google Cloud / Firebase / Maps API key.',
  },
  {
    id: 'slack-bot-token',
    name: 'Slack Bot / User OAuth Token',
    provider: 'Slack',
    severity: SEVERITY.CRITICAL,
    pattern: /\b(xox[baprs]-[0-9a-zA-Z]{10,48}-[0-9a-zA-Z]{10,48}(?:-[0-9a-zA-Z]{10,48})?)\b/g,
    description: 'Slack application authorization token.',
  },
  {
    id: 'slack-webhook',
    name: 'Slack Incoming Webhook URL',
    provider: 'Slack',
    severity: SEVERITY.HIGH,
    pattern: /\b(https:\/\/hooks\.slack\.com\/services\/T[a-zA-Z0-9_]{8,12}\/B[a-zA-Z0-9_]{8,12}\/[a-zA-Z0-9_]{24})\b/g,
    description: 'Slack incoming webhook allowing channel message injection.',
  },
  {
    id: 'discord-bot-token',
    name: 'Discord Bot Token',
    provider: 'Discord',
    severity: SEVERITY.CRITICAL,
    pattern: /\b([MN][A-Za-z\d]{23,26}\.[A-Za-z\d_-]{6}\.[A-Za-z\d_-]{27,38})\b/g,
    description: 'Authentication token for Discord bot operations.',
  },
  {
    id: 'discord-webhook',
    name: 'Discord Webhook URL',
    provider: 'Discord',
    severity: SEVERITY.HIGH,
    pattern: /\b(https:\/\/discord(?:app)?\.com\/api\/webhooks\/[0-9]{17,20}\/[A-Za-z0-9_-]{60,68})\b/g,
    description: 'Direct channel webhook for Discord guild notifications.',
  },
  {
    id: 'telegram-bot-token',
    name: 'Telegram Bot API Token',
    provider: 'Telegram',
    severity: SEVERITY.HIGH,
    pattern: /\b([0-9]{9,10}:[a-zA-Z0-9_-]{35})\b/g,
    description: 'Telegram BotFather generated bot control credential.',
  },
  {
    id: 'private-key',
    name: 'Cryptographic Private Key Block',
    provider: 'PKI / SSH',
    severity: SEVERITY.CRITICAL,
    pattern: /-----BEGIN (?:RSA|OPENSSH|DSA|EC|PGP) PRIVATE KEY[A-Z ]*-----/g,
    description: 'Asymmetric private key header for servers or code signing.',
  },
  {
    id: 'database-connection-string',
    name: 'Database Connection String with Credentials',
    provider: 'Database',
    severity: SEVERITY.CRITICAL,
    pattern: /\b(?:postgres|postgresql|mysql|mongodb|mongodb\+srv|redis):\/\/[a-zA-Z0-9_.-]+:(?:(?!\$\{)[^@\s]+)@[a-zA-Z0-9.-]+(?::[0-9]+)?\/[a-zA-Z0-9_.-]*/gi,
    description: 'Full database connection URI containing plaintext passwords.',
  },
  {
    id: 'jwt-token',
    name: 'JSON Web Token (JWT)',
    provider: 'Identity / Auth',
    severity: SEVERITY.MEDIUM,
    pattern: /\b(eyJ[a-zA-Z0-9_-]{10,}\.eyJ[a-zA-Z0-9_-]{10,}\.[a-zA-Z0-9_-]{10,})\b/g,
    description: 'Base64 encoded signed JSON Web Token containing claims.',
  },
  {
    id: 'generic-hardcoded-secret',
    name: 'Generic High-Entropy Credential Assignment',
    provider: 'Generic',
    severity: SEVERITY.HIGH,
    pattern: /(?:password|passwd|api_key|apikey|secret_key|secretkey|auth_token)\s*[:=]\s*["']([^"'\\s]{12,})["']/gi,
    matchGroup: 1,
    requiresEntropy: true,
    minEntropy: 3.8,
    description: 'High-entropy credential assigned to a sensitive variable name.',
  },
];
